microlinkhq/metascraper

lib/index.js
test/server.js

Currently, the URL returned by the fallback from the url rule is not actually useful, as it's the requested URL rather than the resolved URL (after redirects). This allows the user to obtain the requested URL instead by overriding the rules for URL.
Note that `og:url` and `twitter:url` don't really seem very useful as well - for example, Google uses the URL of their daily doodle here rather than the actual homepage - so it may be worth reconsidering the general usage of this field.

Returns resolved URL rather than requested URL

---

Readme.md
lib/index.js

As proposed in #34 and as I also needed the possibility to pass custom headers to scrapeUrl I made this pull request.
To maintain backwards compatibility I modified the scrapeUrl method so that either a string (url) or an object (containing of url and a headers object) can be passed as first argument. I also mentioned this in the Readme.md.

Passing headers to scrapeUrl

---

packages/metascraper-title/index.js

Some sites have multiple `<title>` elements. (Not sure why)
ie. https://twitter.com => `title: "Twitter. It’s what’s happening.bird"`
(this url also also breaks the [Microlink.io](https://microlink.io) UI)
This fix returns the primary (first) `title` element on the page.

Title only returns first element value

---

packages/metascraper/package.json
packages/metascraper/src/load-html.js

cheerio by default doesn't support pseudo selector.
This PR enable it!
Ideally, I want to add a more complete package for add this functionality, but it needs to be adapted in order to don't break the current interface: 
https://github.com/mrcoles/pseudo-cheerio/issues/3

Add pseudo dom selectors support

---

packages/metascraper-clearbit-logo/README.md
packages/metascraper-clearbit-logo/index.js

Clearbit offers a `greyscale` option as seen [here](https://clearbit.com/docs?javascript#name-to-domain-api-http-response-http-get-params). Would be cool to have it in metascraper 🎬!

Add greyscale option to Clearbit logo API

---

packages/metascraper-date/index.js
packages/metascraper/__snapshots__/index.js.snap-shot
packages/metascraper/test/integration/health/index.js
packages/metascraper/test/integration/health/input.html

Here is an example page which currently has an incorrectly parsed date:
https://www.health.govt.nz/about-ministry/legislation-and-regulation/regulatory-impact-statements/quality-improvement-agency-health-quality-and-safety-commission-functions-powers-and-funding
The HTML which is extracted to find the date string is
```html
<p class="page_updated">Page last updated: <span class="date">07 April 2011</span></p>
```
Currently the extracted date is `201107-04-07` because the selector matches multiple elements (`p.page_updated`, `span.date`) which overlap resulting in the extracted text being:
```
"Page last updated: 07 April 201107 April 2011"
```
This pull request fixes this bug by mapping over each matched element and attempting to parse it as a date, returning the first successful match …

Fix metascraper-date's incorrect parsing of dates

---

packages/metascraper-soundcloud/test/index.js
packages/metascraper/package.json
packages/metascraper/src/get-data.js
packages/metascraper/src/index.js
packages/metascraper/test/unit/xss/files/issue-96.html
packages/metascraper/test/unit/xss/xss.js

Original code from pull request #142 
Closes #96
Closes #153

Add escape parameter to escape html data by default

---

packages/metascraper-title/index.js

Hi,
I came across [this website](https://ministryofstartups.com/), which doesn't have any of the social meta tags (`'og:title'`, `'twitter:title'`), but has multiple `.entry-title` classes. This caused the package to create a really long, somewhat nonsensical title for this page.
I think it only really makes sense to use a `.entry-title` selector when there is only one present on the page.
Let me know what you think of this change.
Cheers.

fix: only use entry-title selector when only one entry-title exists

---

packages/metascraper-helpers/index.js
packages/metascraper-helpers/package.json
packages/metascraper-helpers/test/index.js

The current implementation of the `$jsonld` uses `jsonld` which is wrapped by `mem`.
Unfortunately, because the use of `mem` does not actually specify any cache limitations, all cache entries are just persisted forever. This means that if at any point you scrape the same URL twice, updates to the `script[type="application/ld+json"]` on the page will never be parsed, forcing you to restart the server.
I don't think this was intentional behaviour, so this PR replaces use of `mem` with `memoize-one` which is used elsewhere in the codebase already. This will only cache the result for the last invoked call, which for the purposes of what caching the parse results of `jsonld` achieves, is the same, without the same drawbacks for subsequent calls with the same URL, but different content.

[metascraper-helpers] jsonld caching

---

packages/metascraper/src/load-html.js

these options are related to htmlparser2: https://github.com/fb55/htmlparser2/wiki/Parser-options
they are used only on XML mode, so they are not necessary in this case.

build: remove unnecessary options

---

packages/metascraper-helpers/index.js
packages/metascraper-helpers/package.json

The package [url-regex](https://www.npmjs.com/package/url-regex) has a [Regular Expression Denial of Service vulnerability](https://www.npmjs.com/advisories/1550) and it looks like it is [not maintained anymore](https://github.com/kevva/url-regex/issues/70).
This PR replaces url-regex with [url-regex-safe](https://www.npmjs.com/package/url-regex-safe) which solves the problem above while providing a drop-in replacement for url-regex.

fix: Use url-regex-safe to fix url-regex vulnerability

---

packages/metascraper/index.d.ts
packages/metascraper/package.json

I was integrating your parser in a TypeScript so I figured I could give you the `.d.ts` I've created :smiley: 
What it does:
* Adds an index.d.ts for `metaparser` module
* Adds a global declaration for `metaparser-*` module
* Import Cheerio's typing
The module is use exactly as in Node.js.

Adds type declaration for TypeScript

---

README.md

Fixes descriptions on the documentation. The address and shopping rule bundles' descriptions were inverted.

doc: fixed community rule bundles description

---

packages/metascraper/src/get-data.js

build(perf): avoid to cache array length

---

packages/metascraper-video/index.js
packages/metascraper-video/test/index.js
packages/metascraper/__snapshots__/index.js.snap-shot

I noticed metascraper was not returning videos for this page despite having a video url provided in a twitter meta tag
https://www.outsideonline.com/2403038/elyse-saugstad-cody-townsend-couples-therapy
There are two things going on in this PR:
- Duplicated existing rules to a variant which enables pulling from meta tags with `name` attribute instead of just `property` attribute. The [twitter card validator ](https://cards-dev.twitter.com/validator) verifies the tags at the url above, so even though this format isn't called out it appears to be valid.
- adds a new rules for the tag `twitter:player` which is exhibited at the url above.

feat: add support for meta name & twitter:player video urls

---

packages/metascraper-author/index.js
packages/metascraper-video/test/fixtures/video-src.html
packages/metascraper/test/integration/medium/input.html
packages/metascraper/test/integration/washington-post/input.html

I re-download the HTML markup related to the integration tests.
some interesting thing:
- just the verge still has wrong markup ([tweet](https://twitter.com/Kikobeats/status/1368961061274214400)).
- the washington post doesn't have markup ([tweet](https://twitter.com/Kikobeats/status/1368964702366269448)).

metascraper-author: remove invalid markup support

---

packages/metascraper-audio/index.js

This is a continuation of https://github.com/microlinkhq/metascraper/pull/379 but for metascraper-audio

fix: use name instead of property

---

packages/metascraper-logo-favicon/index.js

This pull request fixes a `TypeError: pickDefault is not a function` error when using the [example usage](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-logo-favicon/README.md) favicon code. It looks as if the `pickBuggerSize` argument was removed perhaps by accident in https://github.com/microlinkhq/metascraper/pull/326/files#diff-74e05d3ffe4f477374555aa80848c0c82ca02139bf21197c13f8d81c4e0f9772R90.

fix(favicon): pass default function

---

packages/metascraper-helpers/index.js

lodash isEmpty considers numbers (and booleans) an empty value (https://lodash.com/docs/4.17.10#isEmpty), so it is not possible to scape numbers properly. 
For example if you try to scrape prices with the following rules, and 'price' has a value (for example 25.5), but 'offers.price' and '0.offers.price' does not, it will loop though the remaining fields and you end up with no value. 
```
price: [
({htmlDom: $, url}: type) => $jsonld('price')($, url),
({htmlDom: $, url}: type) => $jsonld('offers.price')($, url),
({htmlDom: $, url}: type) => $jsonld('0.offers.price')($, url),
]
``` 
Wasn't sure if I should file an issue or a PR, or if this behavior is intended for some reason, but would love to see a fix/workaround for this 😊

fix(helpers): JSON+LD detects number pproperly

---

packages/metascraper-clearbit/index.js
packages/metascraper-helpers/index.js
packages/metascraper-helpers/test/index.js
packages/metascraper-iframe/src/from-html.js
packages/metascraper-iframe/src/from-provider.js
packages/metascraper-logo-favicon/index.js

use undefined instead.
Related: https://github.com/sindresorhus/meta/discussions/7

feat: avoid null

---

packages/metascraper-amazon/index.js
packages/metascraper-iframe/src/index.js
packages/metascraper-iframe/test/index.js
packages/metascraper-instagram/index.js
packages/metascraper-media-provider/README.md
packages/metascraper-media-provider/bench/constants.js
packages/metascraper-media-provider/bench/provider/generic.js
packages/metascraper-media-provider/bench/provider/twitter/guest-token.js
packages/metascraper-media-provider/bench/provider/twitter/index.js
packages/metascraper-media-provider/package.json
packages/metascraper-media-provider/src/get-media/index.js
packages/metascraper-media-provider/src/get-media/provider/generic.js
packages/metascraper-media-provider/src/get-media/provider/twitter.js
packages/metascraper-media-provider/src/get-media/util.js
packages/metascraper-spotify/README.md
packages/metascraper-spotify/index.js
packages/metascraper-spotify/package.json
packages/metascraper-telegram/index.js

- Add `gotOpts` support.
- Removed `keepalive-proxy-agent` dependency, use `getAgent` instead.

feat: unify `gotOpts`

---

packages/metascraper-logo-favicon/README.md
packages/metascraper-logo-favicon/index.js
packages/metascraper-logo-favicon/package.json

Using a function memoizer. This is a necessary thing in this case because http agent only cache succesful/redirect responses.
In this very particular cases, the most common scenario is favicon is missing (404).
Since keyv doesn't store `undefined`, in that case we convert it to `null` and then back to `undefined`.

perf(logo-favicon): memoize urls resolution

---

packages/metascraper-logo-favicon/index.js
packages/metascraper-logo-favicon/package.json
packages/metascraper-logo-favicon/test/index.js

This new rule is oriented for resolving favicon.ico at subdomain urls.
e.g., cdn.teslahunt.io/favicon.ico will be missing, but teslahunt.io/favicon.io will be available.

feat(logo-favicon): root domain resolution

---

packages/metascraper-audio/index.js
packages/metascraper-helpers/index.js
packages/metascraper-helpers/test/load-iframe.js
packages/metascraper-manifest/index.js
packages/metascraper/test/integration/bfi/input.html

The current `metascraper-audio` implementation is trying to apply audio rules over the first iframe detected on the site:
```js
const src = $filter($, iframe, el => normalizeUrl(url, el.attr('src')))
```
I noted some sites has third-party ads service that inject iframe, so the current implementation is not going to detect nothing, even the site could have other iframes with audio content.
What could be a better approach is to resolve audio rules per all iframes present. This is reasonably fast if it's done in parallel and only wait for the first audio iframe in the best case.

metascraper-audio: better iframe detection

---

packages/metascraper-helpers/index.js

Normally I don't put much attention in micro benchmarking, but startup time is a thing.
https://measurethat.net/Benchmarks/Show/3431/0/spread-vs-mutation-vs-objectassign-for-reduce-callback

perf: avoid spread for initialization 

---

packages/metascraper-amazon/index.js
packages/metascraper-amazon/package.json
packages/metascraper-clearbit/index.js
packages/metascraper-clearbit/package.json
packages/metascraper-helpers/index.js
packages/metascraper-helpers/test/index.js
packages/metascraper-instagram/index.js
packages/metascraper-instagram/package.json
packages/metascraper-logo-favicon/index.js
packages/metascraper-logo-favicon/package.json
packages/metascraper-media-provider/package.json
packages/metascraper-media-provider/src/get-media/util.js
packages/metascraper-soundcloud/index.js
packages/metascraper-soundcloud/package.json
packages/metascraper-spotify/index.js
packages/metascraper-spotify/package.json
packages/metascraper-telegram/index.js
packages/metascraper-uol/index.js

The goal is to avoid reparse values already computed previously.
This PR unifies `tldts` inside metascraper helper, wrapped by `lodash.memoize`.
A little benchmark performed inside tests:
- first method call: 0.30225ms
- successive calls: 0.016458ms

perf: unify tldts

---

README.md
packages/metascraper-helpers/index.js
packages/metascraper-helpers/package.json

feat: be possible to skip re2

---

packages/metascraper/package.json
packages/metascraper/src/index.d.ts
packages/metascraper/test/types/index.test-d.ts

Closes https://github.com/microlinkhq/metascraper/issues/666
Closes https://github.com/microlinkhq/metascraper/issues/657

feat: better type definitions

---

packages/metascraper-logo-favicon/package.json

Fixes `.d.ts` file export  in package.json so types can be properly discovered.

fix(metascraper-logo-favicon): types reference in package.json

---

package.json
packages/metascraper-helpers/index.js
packages/metascraper-helpers/package.json
packages/metascraper-helpers/test/index.js
packages/metascraper-logo-favicon/src/index.js
packages/metascraper-logo-favicon/test/index.js
packages/metascraper-logo/src/index.js
packages/metascraper-telegram/src/index.js

Since logo can be detected from HTML markup there is the case where the data URI detected is empty. an empty data uri ('data:,') is considered a valid URL & URI, but can't be considered a valid image.

fix(logo): avoid data uri with no length

---

packages/metascraper/src/index.d.ts

Fix an issue with types not working correctly in `module: node16` in TypeScript.
See: https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseExportDefault.md

fix: work with tsconfig `module: node16` in ESM

---

packages/metascraper-video/package.json

[p-reflect](https://www.npmjs.com/package/p-reflect/v/2.1.0) is not a dependency of metascraper-video but it requires it here:
https://github.com/microlinkhq/metascraper/blob/8e964f23d760062c77e7513d1d3e87416c511499/packages/metascraper-video/src/index.js#L15

fix metascraper-video missing p-reflect in package.json

---

packages/metascraper-readability/README.md
packages/metascraper-readability/package.json
packages/metascraper-readability/src/index.d.ts
packages/metascraper-readability/src/index.js
packages/metascraper-readability/src/worker.js

`happy-dom` throws unhandled exceptions based on the target URL markup, so there is no way to don't pullate the main Node.js process.

chore(readability): use worker threads

---

packages/metascraper/src/index.d.ts

This change refactors the Rules type in index.d.ts to eliminate the conflicting index‑signature behaviour and support both:
1. Strongly‑typed named metadata keys
We introduce a NamedRules mapped type that only includes the literal keys of Metadata, so plugins get proper autocompletion and excess‑property checking on known fields.
2. test and pkgName properties
We extend NamedRules with the two special properties `test?: (opts: RulesTestOptions) => boolean` and `pkgName?: string` so they no longer clash with the generic rule‑function signature.
3. Single unified index signature
A single [key: string]: … signature now covers:
- rule‑functions (RulesOptions or RulesOptions[]),
- the test function,
- the pkgName string,
- any other ad‑hoc metadata keys.
Why is this needed?
When adding pkgName …

fix(types): Allow test and pkgName in Rules while preserving generic metadata keys

---

packages/metascraper-readability/src/worker.js

I noted global scope is polluted by errors propagated to Node.js process produced by happy-dom
I discovered this package https://www.npmjs.com/package/@happy-dom/uncaught-exception-observer
but it's not necessary since this is now a builtin feature and we should to start using it.

chore(readability): avoid errors propagation
