- Readme.md
Fix a dead link in the Table of Contents
Fix the "Override" term
> Fix TOC link + wording.

- packages/metascraper-author/index.js
- packages/metascraper-helpers/index.js
- packages/metascraper-video/.npmrc
- packages/metascraper-video/README.md
- packages/metascraper-video/__snapshots__/index.js.snap-shot
- packages/metascraper-video/index.js
- packages/metascraper-video/package.json
- packages/metascraper-video/test/.metascraperrc
- packages/metascraper-video/test/fixtures/source-src.html
- packages/metascraper-video/test/fixtures/video-src.html
- packages/metascraper-video/test/index.js
- packages/metascraper-video/test/mocha.opts
- packages/metascraper-youtube/index.js
> Add metascraper-video

- packages/metascraper-media-provider/package.json
- packages/metascraper-media-provider/src/get-media/twitter-info.js
- packages/metascraper/package.json
It makes easy reach the API limit. Instead get auth and guest token from markup.
Inspiration: https://github.com/loklak/loklak_server/blob/7c513ae7949718399a7cf06bb19e80da362ef396/src/org/loklak/harvester/TwitterScraper.java#L486-L506
> Avoid use Twitter API

- packages/metascraper-media-provider/src/get-media/get-media.js
Related: https://github.com/przemyslawpluta/node-youtube-dl/issues/128\#issuecomment-253184229
> fix: ensure buffer has enough space

- packages/metascraper-amazon/package.json
- packages/metascraper-audio/package.json
- packages/metascraper-author/package.json
- packages/metascraper-clearbit-logo/package.json
- packages/metascraper-date/package.json
- packages/metascraper-description/package.json
- packages/metascraper-helpers/package.json
- packages/metascraper-image/package.json
- packages/metascraper-lang/package.json
- packages/metascraper-logo-favicon/package.json
- packages/metascraper-logo/package.json
- packages/metascraper-media-provider/package.json
- packages/metascraper-publisher/package.json
- packages/metascraper-readability/package.json
- packages/metascraper-soundcloud/package.json
- packages/metascraper-title/package.json
- packages/metascraper-url/package.json
- packages/metascraper-video/package.json
- packages/metascraper-youtube/package.json
> build: update package readme link

- packages/metascraper-clearbit-logo/index.js
- packages/metascraper-logo-favicon/index.js
- packages/metascraper-media-provider/src/get-media/twitter-info.js
> fix: ensure external requests has early timeout

- packages/metascraper-media-provider/README.md
- packages/metascraper-media-provider/package.json
- packages/metascraper-media-provider/src/get-media/constant.js
- packages/metascraper-media-provider/src/get-media/get-media.js
- packages/metascraper-media-provider/src/get-media/index.js
- packages/metascraper-media-provider/src/get-media/twitter-info.js
- packages/metascraper-media-provider/src/index.js
- packages/metascraper-media-provider/test/index.js
it delegates into `luminati-tunnel` that uses round robin approach. Also, added documentation about all the options available and pass them properly.
> feat: improve proxy support

- packages/metascraper-helpers/index.js
- packages/metascraper-helpers/test/index.js
- packages/metascraper-image/index.js
- packages/metascraper-title/index.js
- packages/metascraper-youtube/__snapshots__/index.js.snap-shot
- packages/metascraper/__snapshots__/index.js.snap-shot
- packages/metascraper/__snapshots__/xss.js.snap-shot
- packages/metascraper/test/integration/washington-post/input.html
- packages/metascraper/test/unit/interface.js
- packages/metascraper/test/unit/xss.js
> Improve titles detection 

- package.json
- packages/metascraper-amazon/package.json
- packages/metascraper-clearbit/README.md
- packages/metascraper-clearbit/__snapshots__/index.js.snap-shot
- packages/metascraper-clearbit/index.js
- packages/metascraper-clearbit/package.json
- packages/metascraper-clearbit/test/index.js
- packages/metascraper-helpers/index.js
- packages/metascraper-logo-favicon/index.js
- packages/metascraper-logo-favicon/package.json
- packages/metascraper-logo-favicon/test/fixtures/input.html
- packages/metascraper-logo-favicon/test/index.js
- packages/metascraper-media-provider/src/get-media/provider/generic.js
- packages/metascraper-media-provider/src/get-media/provider/twitter.js
- packages/metascraper-soundcloud/package.json
- packages/metascraper-uol/package.json
Closes #196
Closes #197
Closes #198
Beware: I'm not actually sure that this works since I can't run the tests locally and I also don't know how stuff actually gets passed to metascraper rules, being the first one i've edited; #197 for details. Therefore this doesn't have updated snapshots.
> [metascraper-clearbit] expose some package options

- packages/metascraper-amazon/index.js
- packages/metascraper-amazon/package.json
- packages/metascraper-clearbit/index.js
- packages/metascraper-clearbit/package.json
- packages/metascraper-helpers/index.js
- packages/metascraper-media-provider/package.json
- packages/metascraper-media-provider/src/get-media/index.js
- packages/metascraper-readability/index.js
- packages/metascraper-readability/package.json
- packages/metascraper-soundcloud/index.js
- packages/metascraper-soundcloud/package.json
- packages/metascraper-uol/index.js
- packages/metascraper-uol/package.json
- packages/metascraper-uol/test/index.js
- packages/metascraper-video/index.js
- packages/metascraper-youtube/index.js
- packages/metascraper-youtube/package.json
- packages/metascraper-youtube/test/index.js
- packages/metascraper/src/get-data.js
- packages/metascraper/test/unit/interface.js
not only the url, also take into consideration the html.
Unified `memoizeOne` as part of `@metascraper/helpers`
> build: deterministic memoize

- packages/metascraper-iframe/src/from-html.js
- packages/metascraper-iframe/src/from-provider.js
- packages/metascraper-iframe/src/index.js
- packages/metascraper-iframe/test/index.js
Extracted from https://github.com/TryGhost/Ghost/blob/b91f3071be893c7092541855c023a34a496f5d02/core/server/api/canary/oembed.js#L89
> build: handle www and non-www for providers

- packages/metascraper-description/index.js
- packages/metascraper-description/package.json
- packages/metascraper-description/test/index.js
- packages/metascraper-description/test/mocha.opts
- packages/metascraper-media-provider/test/index.js
> fix: ensure to pass description options

- packages/metascraper-helpers/index.js
- packages/metascraper-helpers/test/index.js
> fix: ensure to accept urls with parens

- .travis.yml
- package.json
- packages/metascraper-amazon/package.json
- packages/metascraper-audio/package.json
- packages/metascraper-author/package.json
- packages/metascraper-clearbit/package.json
- packages/metascraper-date/package.json
- packages/metascraper-description/package.json
- packages/metascraper-helpers/index.js
- packages/metascraper-helpers/package.json
- packages/metascraper-iframe/package.json
- packages/metascraper-image/package.json
- packages/metascraper-lang/package.json
- packages/metascraper-logo-favicon/package.json
- packages/metascraper-logo/package.json
- packages/metascraper-media-provider/package.json
- packages/metascraper-publisher/package.json
- packages/metascraper-readability/package.json
- packages/metascraper-soundcloud/package.json
- packages/metascraper-spotify/package.json
- packages/metascraper-title/package.json
- packages/metascraper-uol/package.json
- packages/metascraper-url/package.json
- packages/metascraper-video/package.json
- packages/metascraper-youtube/package.json
- packages/metascraper/__snapshots__/index.js.snap-shot
- packages/metascraper/package.json
> build: use url-regex-safe instead of url-regex

- packages/metascraper-helpers/index.js
- packages/metascraper-media-provider/src/index.js
- packages/metascraper-media-provider/test/fixtures/extension/mpga.json
- packages/metascraper-media-provider/test/index.js
> fix: add mpga audio extension

- packages/metascraper-media-provider/package.json
- packages/metascraper-media-provider/src/get-media/provider/generic.js
> build: use a better youtube-dl dependency

- packages/metascraper-amazon/package.json
- packages/metascraper-audio/package.json
- packages/metascraper-author/index.js
- packages/metascraper-clearbit/package.json
- packages/metascraper-helpers/index.js
- packages/metascraper-media-provider/package.json
- packages/metascraper-soundcloud/package.json
- packages/metascraper-spotify/package.json
- packages/metascraper-telegram/package.json
- packages/metascraper-uol/package.json
- packages/metascraper-video/package.json
- packages/metascraper/__snapshots__/index.js.snap-shot
- packages/metascraper/package.json
> fix(author): be sure byline rule is not a date

- packages/metascraper-helpers/index.js
update `value` with the trimmed value
> fix: retain trim value

- packages/metascraper-audio/__snapshots__/index.js.snap-shot
- packages/metascraper-audio/index.js
- packages/metascraper-audio/test/index.js
- packages/metascraper-iframe/src/from-twitter.js
- packages/metascraper-iframe/src/index.js
- packages/metascraper-iframe/test/fixtures/indiehacker.html
- packages/metascraper-iframe/test/index.js
- packages/metascraper-video/__snapshots__/index.js.snap-shot
- packages/metascraper-video/index.js
- packages/metascraper-video/test/index.js
> metascraper-iframe: add twitter player iframe support

- packages/metascraper-helpers/__snapshots__/index.js.snap-shot
- packages/metascraper-helpers/index.js
- packages/metascraper-helpers/test/index.js
- packages/metascraper/__snapshots__/index.js.snap-shot
- packages/metascraper/test/integration/vice/input.html
A JSON-LD structure can be defined using `@graph` property rather than just a single node.
```JSON
{
"@context": {
"generatedAt": {
"@id": "http://www.w3.org/ns/prov#generatedAtTime",
"@type": "http://www.w3.org/2001/XMLSchema#dateTime"
},
"Person": "http://xmlns.com/foaf/0.1/Person",
"name": "http://xmlns.com/foaf/0.1/name",
"knows": {"@id": "http://xmlns.com/foaf/0.1/knows", "@type": "@id"}
},
"@id": "http://example.org/foaf-graph",
"generatedAt": "2012-04-09T00:00:00",
"@graph": [
{
"@id": "http://manu.sporny.org/about#manu",
"@type": "Person",
"name": "Manu Sporny",
"knows": "https://greggkellogg.net/foaf#me"
}, {
"@id": "https://greggkellogg.net/foaf#me",
"@type": "Person",
"name": "Gregg Kellogg",
"knows": "http://manu.sporny.org/about#manu"
}
]
}
```
This PR normalizes the `@graph` …
> feat(helpers): add JSON-LD @graph support

- README.md
> docs: improve user walkthrough

- package.json
- packages/metascraper-feed/.npmrc
- packages/metascraper-feed/CHANGELOG.md
- packages/metascraper-feed/README.md
- packages/metascraper-feed/index.js
- packages/metascraper-feed/package.json
- packages/metascraper-feed/test/index.js
This PR adds a new metascraper plugin to get the RSS/Atom/JSON feed from a page.
> feat(metascraper-feed): create new feed plugin

- packages/metascraper/src/index.d.ts
> fix: update Typescript types

- package.json
- packages/metascraper-amazon/package.json
- packages/metascraper-audio/package.json
- packages/metascraper-author/package.json
- packages/metascraper-clearbit/package.json
- packages/metascraper-date/package.json
- packages/metascraper-description/package.json
- packages/metascraper-feed/package.json
- packages/metascraper-helpers/package.json
- packages/metascraper-iframe/package.json
- packages/metascraper-image/package.json
- packages/metascraper-instagram/package.json
- packages/metascraper-lang/package.json
- packages/metascraper-logo-favicon/package.json
- packages/metascraper-logo/package.json
- packages/metascraper-manifest/package.json
- packages/metascraper-media-provider/package.json
- packages/metascraper-publisher/package.json
- packages/metascraper-readability/package.json
- packages/metascraper-soundcloud/package.json
- packages/metascraper-spotify/package.json
- packages/metascraper-telegram/package.json
- packages/metascraper-title/package.json
- packages/metascraper-twitter/package.json
- packages/metascraper-uol/package.json
- packages/metascraper-url/package.json
- packages/metascraper-video/package.json
- packages/metascraper-youtube/package.json
- packages/metascraper/package.json
matching https://github.com/jsdom/jsdom/blob/a39e0ec4ce9a8806692d986a7ed0cd565ec7498a/package.json#L90C14-L90C18
closes https://github.com/microlinkhq/metascraper/issues/652
> fix: use node16 or above

- packages/metascraper-amazon/package.json
- packages/metascraper-audio/package.json
- packages/metascraper-author/package.json
- packages/metascraper-clearbit/package.json
- packages/metascraper-date/package.json
- packages/metascraper-description/package.json
- packages/metascraper-feed/package.json
- packages/metascraper-image/package.json
- packages/metascraper-instagram/package.json
- packages/metascraper-lang/package.json
- packages/metascraper-logo-favicon/package.json
- packages/metascraper-logo/package.json
- packages/metascraper-manifest/package.json
- packages/metascraper-publisher/package.json
- packages/metascraper-readability/package.json
- packages/metascraper-soundcloud/package.json
- packages/metascraper-spotify/package.json
- packages/metascraper-telegram/package.json
- packages/metascraper-title/package.json
- packages/metascraper-twitter/package.json
- packages/metascraper-uol/package.json
- packages/metascraper-video/package.json
- packages/metascraper-youtube/package.json
Catched at https://github.com/microlinkhq/metascraper/pull/677#issuecomment-1861933614
> fix(types): use src folder

- packages/metascraper-image/src/index.js
Remove duplicate `image.url` from `jsonld`
> Remove duplicate json ld image property

- packages/metascraper-media-provider/README.md
- packages/metascraper-media-provider/src/get-media.js
- packages/metascraper-media-provider/src/index.d.ts
> chore(media-provider): delete getAgent

- packages/metascraper-clearbit/package.json
Clearbit Logo API is discontinued 
More info: https://github.com/microlinkhq/metascraper/issues/750
> chore(clearbit): discontinued
